import { useI18nContext } from '@/i18n/i18n-react';
const labels = {
  recreateSections: [
    'This development cue uses the previous section format. Detach it and create a new cue.',
    'Dieser Entwicklungs-Cue verwendet das vorherige Abschnittsformat. Cue lösen und neu erstellen.',
  ],
  timelineKeys: [
    'Timeline keys: ←/→ snap step · Shift+←/→ 1 s · Alt+←/→ section boundary · Home/End · Space play/pause',
    'Zeitleiste: ←/→ Rasterschritt · Umschalt+←/→ 1 s · Alt+←/→ Abschnittsgrenze · Pos1/Ende · Leertaste Wiedergabe/Pause',
  ],
  section: ['Section', 'Abschnitt'],
  sections: ['Sections', 'Abschnitte'],
  noMapping: ['No lyric mapping', 'Keine Textzuordnung'],
  loopSection: ['Loop this section', 'Diesen Abschnitt wiederholen'],
  mainAudio: ['Play audio in the main window', 'Audio im Hauptfenster abspielen'],
  muteMain: ['Mute audio', 'Audio stummschalten'],
  unmuteMain: ['Enable audio', 'Audio aktivieren'],
  mainAudioBlocked: [
    'Audio playback was blocked. Press Play in the main window to retry.',
    'Audiowiedergabe blockiert. Im Hauptfenster Play drücken, um es erneut zu versuchen.',
  ],

  readingDuration: ['Reading duration…', 'Dauer wird gelesen…'],
  durationUnavailable: [
    'Duration unavailable. Set it in Advanced settings.',
    'Dauer nicht verfügbar. In den erweiterten Einstellungen festlegen.',
  ],
  refreshWaveform: ['Refresh waveform', 'Wellenform neu laden'],
  setupHint: [
    'Choose your media, then select the screens. Each screen can show a different crop of the same video.',
    'Medien auswählen, dann Ausgaben wählen. Jede Ausgabe kann einen anderen Ausschnitt desselben Videos zeigen.',
  ],
  chooseScreens: ['Show on these screens', 'Auf diesen Ausgaben anzeigen'],
  noScreens: [
    'Create a presentation window in the window settings to assign media.',
    'Ein Präsentationsfenster in den Fenstereinstellungen erstellen, um Medien zuzuordnen.',
  ],
  advancedMedia: ['Advanced · timing, sources & output roles', 'Erweitert · Zeiten, Quellen & Ausgaberollen'],
  useFile: ['Use this file', 'Diese Datei verwenden'],
  noAudio: ['This file has no audio track.', 'Diese Datei hat keine Audiospur.'],
  codec: [
    'This browser cannot decode the audio codec. Try an AAC or Opus audio track.',
    'Dieser Browser kann den Audiocodec nicht dekodieren. Eine AAC- oder Opus-Audiospur verwenden.',
  ],
  read: [
    'Cannot read the audio track. Check the local media server or the file URL.',
    'Audiospur nicht lesbar. Lokalen Medienserver oder Datei-URL prüfen.',
  ],

  createRegion: ['Add region', 'Bereich hinzufügen'],
  outputClosed: ['Output window closed', 'Ausgabefenster geschlossen'],
  awaitingOutput: ['Waiting for output', 'Warte auf Ausgabe'],
  useDuration: ['Use source duration', 'Quelldauer übernehmen'],
  image: ['Image', 'Bild'],
  cue: ['Media cue', 'Medien-Cue'],
  create: ['Create cue', 'Cue erstellen'],
  edit: ['Sources & screens', 'Quellen & Ausgaben'],
  lyrics: ['Lyrics', 'Liedtext'],
  loop: ['Loop', 'Schleife'],
  pause: ['Pause', 'Pause'],
  save: ['Save', 'Speichern'],
  cancel: ['Cancel', 'Abbrechen'],
  close: ['Close', 'Schließen'],
  remove: ['Delete', 'Löschen'],
  name: ['Name', 'Name'],
  start: ['Beginning', 'Anfang'],
  end: ['Ending', 'Ende'],
  exact: ['Exact timing (seconds)', 'Exakte Zeiten (Sekunden)'],
  mapping: ['Map to lyric block', 'Textblock zuordnen'],
  choose: ['Choose a block', 'Block auswählen'],
  clear: ['Instrumental · clear lyrics', 'Instrumental · Text ausblenden'],
  custom: ['Customize name', 'Namen anpassen'],
  classify: ['Use this region as…', 'Diesen Bereich verwenden als…'],
  editRegion: ['Edit region', 'Bereich bearbeiten'],
  draw: ['Draw over existing regions', 'Über vorhandene Bereiche zeichnen'],
  drag: ['Drag to create', 'Zum Erstellen ziehen'],
  undo: ['Undo edit', 'Bearbeitung rückgängig'],
  play: ['Play / pause', 'Abspielen / pausieren'],
  stop: ['Stop', 'Stopp'],
  exit: ['Exit at end', 'Am Ende verlassen'],
  arm: ['Arm', 'Aktivieren'],
  disarm: ['Disarm', 'Deaktivieren'],
  enabled: ['Enabled', 'Aktiviert'],
  off: ['Off', 'Aus'],
  enable: ['Enable pause', 'Pause aktivieren'],
  disable: ['Disable pause', 'Pause deaktivieren'],
  active: ['Active', 'Aktiv'],
  next: ['Next', 'Als Nächstes'],
  enter: ['Enter loop now', 'Jetzt in Schleife springen'],
  queue: ['Queue after current loop', 'Nach aktueller Schleife einreihen'],
  keep: ['Keep looping', 'Weiter wiederholen'],
  jump: ['Jump to beginning', 'Zum Anfang springen'],
  seekStart: ['Pause and seek to beginning', 'Pausieren und zum Anfang springen'],
  seekEnd: ['Pause and seek to ending', 'Pausieren und zum Ende springen'],
  previewStart: ['Audition beginning · 1 s before, 2 s after', 'Anfang vorhören · 1 s davor, 2 s danach'],
  previewEnd: ['Audition ending · 2 s before, 1 s after', 'Ende vorhören · 2 s davor, 1 s danach'],
  preview: ['Local audition · outputs unchanged', 'Lokal vorhören · Ausgaben unverändert'],
  zoom: ['Zoom', 'Zoom'],
  fit: ['Zoom to selection', 'Auswahl vergrößern'],
  pan: ['Pan', 'Ausschnitt'],
  snap: ['Snap', 'Raster'],
  followVideo: ['Lyrics follow playback', 'Text folgt Wiedergabe'],
  followLyrics: ['Playback follows lyric clicks', 'Wiedergabe folgt Textauswahl'],
  pauseHint: ['Pause at beginning; Play or a section jump continues.', 'Pause am Anfang; Play oder ein Bereichssprung setzt fort.'],
  invalid: ['Check times, sources and screen assignments.', 'Zeiten, Quellen und Ausgaben prüfen.'],
  mismatch: [
    'The arrangement changed. Review and confirm the lyric mappings.',
    'Der Ablauf wurde geändert. Textzuordnungen prüfen und bestätigen.',
  ],
  confirmMapping: ['Confirm this arrangement', 'Diesen Ablauf bestätigen'],
  sources: ['Sources', 'Quellen'],
  addSource: ['Add source', 'Quelle hinzufügen'],
  duration: ['Cue duration (s)', 'Cue-Dauer (s)'],
  offset: ['Source offset (s)', 'Quellversatz (s)'],
  source: ['Source', 'Quelle'],
  audio: ['Audio source', 'Audioquelle'],
  waveform: ['Waveform source', 'Wellenformquelle'],
  owner: ['Audio output', 'Audioausgabe'],
  silent: ['Silent', 'Stumm'],
  screens: ['Screen assignments', 'Ausgabezuordnung'],
  role: ['Output role', 'Ausgaberolle'],
  addScreen: ['Add output role', 'Ausgaberolle hinzufügen'],
  unassigned: ['Unassigned', 'Nicht zugeordnet'],
  noMedia: ['No media', 'Keine Medien'],
  framing: ['Frame & effects', 'Ausschnitt & Effekte'],
  crop: ['Source crop', 'Quellausschnitt'],
  placement: ['Screen placement', 'Ausgabeposition'],
  scale: ['Scale (%)', 'Skalierung (%)'],
  blur: ['Blur', 'Unschärfe'],
  contain: ['Fit entire crop', 'Gesamten Ausschnitt einpassen'],
  cover: ['Fill placement', 'Fläche füllen'],
  fill: ['Stretch', 'Strecken'],
  reset: ['Reset', 'Zurücksetzen'],
  loading: ['Loading waveform…', 'Wellenform wird geladen…'],
  unavailable: ['Waveform unavailable; timeline editing still works.', 'Wellenform nicht verfügbar; Zeitleiste bleibt bearbeitbar.'],
  error: ['Media could not be loaded.', 'Medien konnten nicht geladen werden.'],
  buffering: ['Buffering…', 'Wird gepuffert…'],
  playback: [
    'Playback blocked. Click the output window, then press Play again.',
    'Wiedergabe blockiert. Ausgabefenster anklicken, dann erneut Play drücken.',
  ],
  ready: ['Ready', 'Bereit'],
  retry: ['Retry', 'Erneut versuchen'],
  monitor: ['Monitor audio', 'Audio vorhören'],
  attach: ['Use existing cue', 'Vorhandenen Cue verwenden'],
  detach: ['Detach cue', 'Cue lösen'],
  shared: ['Shared cue · edits affect all linked show items', 'Gemeinsamer Cue · Änderungen gelten für alle verknüpften Show-Elemente'],
  duplicate: ['Duplicate cue', 'Cue duplizieren'],
  paused: ['Paused here', 'Hier pausiert'],
  pending: ['No source selected', 'Keine Quelle ausgewählt'],
  saved: ['Cue saved in show · save the show to upload', 'Cue in Show gespeichert · Show speichern zum Hochladen'],
} as const;
export function useMediaLabels() {
  const { locale } = useI18nContext();
  return (key: keyof typeof labels) => labels[key][locale === 'de' ? 1 : 0];
}
